### ISSUE TITLE
Kein Start bei Proxyverwendung - Proxysupport?

### ISSUE THREAD

**Issue by servidge** [UndertakerBen/PorFirefoxUpd#2]
Hi,

ist eher ein Feature Request und weniger ein wirkliches Problem.
Aber erstmal Danke für das hilfreiches Tool!

Eine Proxyunterstützung wäre hilfreich für Rechner die über keine direkte Internetverbindung besitzen.
Auf einem PC ohne direkte Internetverbindung startet das Programm leider gar nicht. Nach dem ersten WebRequest verschwindet der Prozess nach kurzer Zeit wohl durch einen nicht abgefangenen bzw dann auch nicht ausgegebenen Fehler. Der Nutzer bekommt leider nur mit das nichts passiert.

In meinem Fork habe ich für mich einen erstmal ausreichenden Teil an Fehlerbehandlung bzw Proxynutzung eingebaut damit es funktioniert aber das geht ohne Zweifel deutlich besser. Von einem Pull Request ist der noch sehr weit entfernt.
Das Feature findet vielleicht auch in den anderen Updatern dankbare Verwendung.
Ist vielleicht ja auch schon auf der Roadmap. 

Gruß
Sebastian

**Comment by UndertakerBen** [comment]
Hi,
Ja ich habe da tatsächlich vergessen eine Error Behandlung einzubauen. Das wird im nächsten Release dann behoben sein. Danke!

Was das mit der Proxyunterstützung angeht habe ich bisher keine Erfahrungen damit. Da ich mich damit bisher noch nie beschäftigt hatte und ich auch kein IT-Fachmann bin. Daher weis ich auch nicht was dafür alles benötigt wird. Ob z.B. auch irgendwie ein Passwort benötigt wird oder sonstiges oder ob es genügt die Proxy-Adresse und den Port zu verarbeiten. Habe da jetzt auch mal anhand ihres Forks etwas gespielt und noch zusätzlich die Möglichkeit anhand einer "Proxy.ini" Datei die im selben Ordner wie der Updater gespeichert wird und die Proxy-Adresse mit Port-Nummer enthält eingefügt. 
Beispielinhalt der ini Datei "www-proxy.t-online.de:80".
Hier mal ein Proxy-Test Branch von mir [https://github.com/UndertakerBen/PorFirefoxUpd/tree/Proxy-Test]

Ansonsten bin ich für Hilfe dankbar.

Gruß
Ben

**Comment by UndertakerBen** [comment]
Hi,
Habe jetzt eine neue Version veröffentlicht mit dem Code von Ihnen, damit der Updater auch über einen Proxy Server ins Internet gehen kann.
Nochmals herzlichen Dank für den Request und insbesondere dem Code dafür.
Danke! 

Gruß 
Ben

PS: Ja es wird auch in den anderen Updatern dankbar verwendet werden. 
Danke!

**Comment by servidge** [comment]
Bin leider noch gar nicht dazu gekommen das weiter zu verfolgen. Vielleicht heute Abend.
Aber zu einer "üblichen" Proxynutzung.
Der Proxy müsste auf dem System Abrufbar sein. Bzw mit der Ziel URL kann das Betriebssystem gefragt werden welcher Proxy verwendet werden soll. Das erübrigt dann die Benutzereingabe über ini oder Parameter.
Bei der Proxyverwendung gibt es unterschiedliche Abstufungen die ich bisher gesehen habe.
1. Keine Authentisierung.
Falls der Proxy doch eine Authentisierung verlangt wird er bei fehlender einen Fehler 407 ausgeben.
2. Verwendung des Angemeldeten Benutzer am Betriebssystem. (UseDefaultCredentials)
3. Angabe Username/Passwort

Edit:
Wo ich das gerade mit dem Fehler 407 schreibe und mich daran erinnere wie das Programm anfänglich nicht starten wollte erklärt sich einiges.
Zu dem Zeitpunkt wurde bereits der Defaultproxy vom System verwendet. Der wollte nur eine Authentisierung haben.
Vielleicht hätte ein <defaultProxy useDefaultCredentials="true"> (default ist false) in der app.config gereicht. 

Gruß

**Comment by servidge** [comment]
hat dann doch deutlich länger gedauert. 
Das "Vielleicht hätte ein (default ist false) in der app.config gereicht." hat nicht gereicht. Zumindest nicht in der Umgebung in der ich das getestet habe. Ansonsten funktioniert es dann aber mit den Proxyanpassungen.
